# qadr/constants.py

"""
This file defines the core constants and parameters for the QADR protocol simulation.
Centralizing these values makes it easier to configure and tweak experiments.
"""

# === Cryptographic Parameters ===
# Length of the shared secret keys generated by QKD, in bytes.
# A 256-bit (32-byte) key is a standard choice for strong security.
QKD_KEY_LENGTH_BYTES: int = 32

# Length of the pseudonyms used during the slot reservation phase, in bytes.
# Should be long enough to avoid accidental collisions. 16 bytes = 128 bits.
PSEUDONYM_LENGTH_BYTES: int = 16


# === Protocol Parameters ===
# Default length of a single data message payload, in bytes.
# This will be used in simulations if not specified otherwise.
DEFAULT_MESSAGE_LENGTH_BYTES: int = 128 # 1024 bits, as used in the paper's cost analysis

# The ratio of available slots to the number of participants (gamma = m/n).
# The paper's analysis suggests that gamma=3 is an optimal trade-off.
DEFAULT_SLOT_PARTICIPANT_RATIO: float = 3.0


# === Simulation Parameters ===
# The default number of participants for a single simulation run.
DEFAULT_NUM_PARTICIPANTS: int = 50

# Default number of simulation runs for statistical analysis in experiments.
# A higher number provides more reliable statistics.
DEFAULT_EXPERIMENT_RUNS: int = 100
